server:
  port: 8082

spring:
  application:
    name: alita-server

eureka:
  instance: 
    hostname: alita-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://alita-server:8082/eureka/
