server:
  port: 8083

spring:
  application:
    name: leaf-server

spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request

eureka:
  instance: 
    hostname: leaf-server
  client:
    serviceUrl:
      defaultZone: http://alita-server:8082/eureka/
